Added Ripple LabVIEW Measurement
NI-Measurement-Plug-Ins/pmic-labview pull request #6
Opened 2024-04-02 08:57 UTC by prajwal-jarali

Added the LabVIEW Ripple Measurement
* This measurement aims to measure the ripples produced in the supply by buck converter.

3 Modes of Operation are supported: -
1) Power ON DUT (To turn on Voltage supplier for DUT)
2) Perform Measurement (To completely measure ripples and give results on readings)
3) Power OFF DUT (To turn off Source and Load for DUT)

Tested on buck converter hardware with following results: -
* Power on DUT
<img width="945" alt="image (35)" src="https://github.com/NI-MeasurementLink-Plug-Ins/pmic-labview/assets/158544608/b966076f-e35f-4a7a-8cc9-2d7107bb6447">

* Perform Measurement
<img width="946" alt="image (36)" src="https://github.com/NI-MeasurementLink-Plug-Ins/pmic-labview/assets/158544608/9e50d814-8bcc-49b4-8696-7b1fe861352a">

* Power off DUT
<img width="942" alt="image (37)" src="https://github.com/NI-MeasurementLink-Plug-Ins/pmic-labview/assets/158544608/3d2f3f29-e815-4678-9502-636a3355bd61">

2024-04-04 19:14 UTC, ngoliNI requested changes

2024-04-04 19:14 UTC, ngoliNI commented on source/measurements/ripple/Ripple_PMIC/Get Measurement Details.vi
Please add 'Annotations' VI and update the measurement details, service class; Refer to the existing measurements.

2024-04-04 19:14 UTC, ngoliNI commented on source/measurements/ripple/Ripple_PMIC/Measurement Logic.vi
Don't use 'update results' VI for updating final results

2024-04-05 11:45 UTC, prajwal-jarali commented on source/measurements/ripple/Ripple_PMIC/Get Measurement Details.vi
updated the measurement details vi

2024-04-05 11:45 UTC, prajwal-jarali commented on source/measurements/ripple/Ripple_PMIC/Measurement Logic.vi
made the changes.

2024-04-08 14:39 UTC, closed without merging